### ISSUE TITLE
TabCorp Coding Dojo - Topics

### ISSUE THREAD

**Issue by rodolfoprr** [Pragmateam/coding-dojo#3]
Let's use this issue to post our ideas of topics / katas that we can be running in future sessions.

You can post a suggestion of a kata that you want to run or make a request of a specific topic you want to practice in the sessions. Then we can use 👍 to vote in each idea.

**Comment by ReenaRajani** [comment]
1. Boilerplate of the latest programming trends and how we can debug them ( if any one has worked on any latest framework/language and want to share it with the team, pain points ..etc )

**Comment by FagnerMartinsBrack** [comment]
Elm and Functional Programming in the web
React and component-based programming

**Comment by alabeduarte** [comment]
Hey everyone,

What do you think if we have new issues for each topic? Maybe it could be easier to track and we can close as we go.
